spring.application.name=api-gateway-keycloak-training

server.port=8085


spring.cloud.gateway.server.webflux.routes[0].id=movie-service-movie-recommendation-system
spring.cloud.gateway.server.webflux.routes[0].uri=lb://movie-service-movie-recommendation-system
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/movies/**



eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://213.199.45.51/realms/ms-realm

