spring.application.name=api-gateway-movie-recommendation-system



server.port=8085


spring.cloud.gateway.server.webflux.routes[0].id=movie-service-movie-recommendation-system
spring.cloud.gateway.server.webflux.routes[0].uri=lb://movie-service-movie-recommendation-system
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/movies/**

spring.cloud.gateway.server.webflux.routes[1].id=recommendation-service-movie-recommendation-system
spring.cloud.gateway.server.webflux.routes[1].uri=lb://recommendation-service-movie-recommendation-system
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/recommendations/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.tracing.sampling.probability=1.0
management.tracing.propagation.type=b3

management.tracing.export.zipkin.endpoint=http://213.199.45.51:9411/api/v2/spans

management.endpoints.web.exposure.include=health,info


spring.cloud.gateway.server.webflux.observability.enabled=true
