spring.application.name=orde-ms

spring.cloud.config.profile=dev
spring.profiles.active=dev

spring.cloud.config.label=main
spring.config.import=optional:configserver:http://localhost:8889
logging.level.org.springframework=INFO

logging.level.org.springframework.boot.context.config=DEBUG
logging.level.org.springframework.cloud.config=DEBUG




#spring.datasource.url=jdbc:postgresql://213.199.45.51:5432/order_ms_dev
#spring.datasource.username=microservice_user
#spring.datasource.password=SuperTajneHaslo123
#spring.datasource.driver-class-name=org.postgresql.Driver